cmake_minimum_required (VERSION 3.18)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_BUILD_TYPE Release)

project ("examples" LANGUAGES CXX)
option (BOOTSTRAP_POSIX "BOOTSTRAP" OFF)
find_package(BLAS REQUIRED)

if(USE_NCCL)
  if(BOOTSTRAP_POSIX)
    message(STATUS "BOOTSTRAP is SLURM-POSIX")
  else()
    message(STATUS "BOOTSTRAP is MPI")
    find_package(MPI REQUIRED)
  endif()
  set(cpp_sources xlra_example.cpp xsvd_example.cpp xsvd_1drow_example.cpp xsvd_2d_example.cpp bootstrap_check.cpp)
else()
  set(cpp_sources xlra_example.cpp xsvd_example.cpp)
endif()

set_source_files_properties(${cpp_sources} PROPERTIES COMPILE_OPTIONS "-Wall;-Wextra;-fexceptions")

foreach (exe ${cpp_sources})
  get_filename_component(src ${exe} NAME_WE)
  add_executable(${src}.app ${exe})
  target_include_directories(${src}.app PRIVATE ${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_CURRENT_SOURCE_DIR}/..)
  target_link_libraries(${src}.app PRIVATE hyacin BLAS::BLAS CUDA::cudart CUDA::cublas CUDA::cusolver)

  if(USE_NCCL)
    target_include_directories(${src}.app PRIVATE ${NCCL_INCLUDE_DIRS})
    target_link_libraries(${src}.app PRIVATE ${NCCL_LIBRARIES})
    if(BOOTSTRAP_POSIX)
      target_compile_definitions(${src}.app PRIVATE "BOOTSTRAP_POSIX")
    else()
      target_link_libraries(${src}.app PRIVATE MPI::MPI_CXX)
    endif()
  else()
    target_compile_definitions(${src}.app PRIVATE "NO_NCCL")
  endif()
endforeach ()

